package com.slice.enums.loanaccountservice;

public enum RepaymentMode {
        E_NACH, PAYMENT_GATEWAY, DEDUCTED_AT_DISBURSEMENT, OPS_PORTAL, EXCESS_PAYMENT, CREDITMATE, BBPS, REFUND_REVERSAL,
        ALLOCATION_REVERSAL, TOP_UP_TRANSFER, ESIGN, UPI, EXCESS_INTEREST, COMBINED_REPAYMENT, NET_BANKING
}
